use wm;
CREATE TABLE IF NOT EXISTS cidades (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	estado_id INT UNSIGNED NOT NULL,
	nome VARCHAR(200) NOT NULL,
	area DECIMAL(10,2),
	PRIMARY KEY (id),
	FOREIGN KEY (estado_id) REFERENCES estados (id)
);